language: node_js
node_js:
  - "6"
  - "6.1"
  - "5.11"
services: mongodb
before_script:
  - npm install
  - npm install -g webpack
  - npm install -g mocha
script:
  - webpack
  - mocha --compilers js:babel-core/register --recursive